name: Bug Report
description: Create if script is not working or there are mistakes in the output.
title: "[Bug]: <add description>"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: dropdown
    id: problem
    attributes:
      label: Problem with script/output
      description: Is the issue with the script or output
      options:
        - Script
        - Output
    validations:
      required: true
  - type: textarea
    id: Description
    attributes:
      label: Error or issue description.
      description: Also tell us, what did you expect to happen?
      placeholder: Description to reproduce the error and a detailed description of error message. In case of mistake in output describe the issue and expected result.
      value: "Describe the Error or issue"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant R-log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
   - type: checkboxes
    id: Confirm
    attributes:
      label: Confirm
      description: Please confirm you have checked, read and understood the following
      options:
        - label: I have checked existing bug-reports and my issue is not listed.
          required: true
        - label: I confirm that this is an issue in the script and/or output and not a feature request.
          required: true
